[tool.poetry]
name = "rockbox-listenbrainz-scrobbler"
version = "0.1.0"
description = ""
authors = ["André Büsgen <andre.buesgen@posteo.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pylistenbrainz = "^0.5.1"
typer = { extras = ["all"], version = "^0.9.0" }
pydantic = "^2.6.1"

[tool.poetry.scripts]
rockbox-listenbrainz = "rockbox_listenbrainz_scrobbler.cli:main"


[tool.poetry.group.dev.dependencies]
pylint = "^3.0.3"
black = "^24.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
