name: Build Package

on:
  push:
    branches:
      - main
      - dev
      - feature/*
      - refactor/*
      - fix/

jobs:
  pyinstaller-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-linux@python3.10
        with:
          spec: rockbox-scrobbler-ui.spec
          path: ./

      - uses: actions/upload-artifact@v2
        with:
          name: rockbox-scrobbler-ui
          path: ./dist/
