name: Build Package

on:
  push:
    branches:
      - main
      - dev
      - feature/*
      - refactor/*
      - fix/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install

    - name: Build package with Poetry
      run: poetry build

    - name: Run PyInstaller on ui.spec
      run: pyinstaller ui.spec

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: dist/*
