name: Build Package

on:
  push:
    branches:
      - main
      - dev
      - feature/*
      - refactor/*
      - fix/

jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'ui.spec'
          requirements: 'pyproject.toml'
          upload_exe_with_name: 'Rockbox Listenbrainz Scrobbler'
          options: --onefile, --name "Rockbox Listenbrainz Scrobbler", --windowed,

  pyinstaller-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'ui.spec'
          requirements: 'pyproject.toml'
          upload_exe_with_name: 'Rockbox Listenbrainz Scrobbler'
          options: --onefile, --name "Rockbox Listenbrainz Scrobbler", --windowed,
